env:
  global:
    - CODECOV_TOKEN="524d3f8f-9070-4c88-8d3a-95817a1fea76"
    - CC_TEST_REPORTER_ID="5e08a0ed8efa585b6dc215b9429b13ebd53107bee3164ba85dc2d59cd394f54f"

sudo: false
language: java

before_script:
  - ./gradlew assemble

  # Set up Code Climate for test reporting
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./gradlew test

after_script:

  # Send coverage result to Code Climate
  - cp ./build/reports/jacoco/test/jacocoTestReport.xml jacoco.xml
  - ./cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT
