env:
  global:
    - CODECOV_TOKEN="524d3f8f-9070-4c88-8d3a-95817a1fea76"
    - CC_TEST_REPORTER_ID="5e08a0ed8efa585b6dc215b9429b13ebd53107bee3164ba85dc2d59cd394f54f"

sudo: false
language: java

before_script:
  # Set up Code Climate for test reporting
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./gradlew build

after_script:
  # Send test coverage results to Codecov
  - bash <(curl -s https://codecov.io/bash)
  # Send coverage result to Code Climate
  - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
